[I 17:45:59.737 NotebookApp] [nb_conda_kernels] enabled, 8 kernels found
[I 17:46:00.824 NotebookApp] The port 8888 is already in use, trying another port.
[I 17:46:00.825 NotebookApp] The port 8889 is already in use, trying another port.
[I 17:46:00.825 NotebookApp] The port 8890 is already in use, trying another port.
[I 17:46:00.826 NotebookApp] The port 8891 is already in use, trying another port.
[I 17:46:00.827 NotebookApp] The port 8892 is already in use, trying another port.
[I 17:46:00.869 NotebookApp] [jupyter_nbextensions_configurator] enabled 0.4.1
[I 17:46:00.908 NotebookApp] JupyterLab extension loaded from /anaconda3/lib/python3.7/site-packages/jupyterlab
[I 17:46:00.909 NotebookApp] JupyterLab application directory is /anaconda3/share/jupyter/lab
[I 17:46:00.916 NotebookApp] [nb_conda] enabled
[I 17:46:00.916 NotebookApp] Serving notebooks from local directory: /Users/ed/Git/Blog/learnPandas/codes
[I 17:46:00.916 NotebookApp] The Jupyter Notebook is running at:
[I 17:46:00.916 NotebookApp] http://localhost:8944/?token=e3062817268348b98ad96ef34bb458d5a233abdf17c09271
[I 17:46:00.916 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 17:46:00.924 NotebookApp] 
    
    To access the notebook, open this file in a browser:
        file:///Users/ed/Library/Jupyter/runtime/nbserver-60033-open.html
    Or copy and paste one of these URLs:
        http://localhost:8944/?token=e3062817268348b98ad96ef34bb458d5a233abdf17c09271
[I 17:48:19.821 NotebookApp] Creating new notebook in 
[I 17:48:21.069 NotebookApp] Kernel started: 33a8c11b-dd4c-4397-a1ab-c8de6141c4bb
[I 17:50:21.064 NotebookApp] Saving file at /sklearn-often.ipynb
[IPKernelApp] WARNING | Parent appears to have exited, shutting down.
nohup: juypter: No such file or directory
[I 09:41:34.623 NotebookApp] [nb_conda_kernels] enabled, 8 kernels found
[I 09:41:35.550 NotebookApp] The port 8888 is already in use, trying another port.
[I 09:41:35.552 NotebookApp] The port 8889 is already in use, trying another port.
[I 09:41:35.552 NotebookApp] The port 8890 is already in use, trying another port.
[I 09:41:35.553 NotebookApp] The port 8891 is already in use, trying another port.
[I 09:41:35.553 NotebookApp] The port 8892 is already in use, trying another port.
[I 09:41:35.589 NotebookApp] [jupyter_nbextensions_configurator] enabled 0.4.1
[I 09:41:35.629 NotebookApp] JupyterLab extension loaded from /anaconda3/lib/python3.7/site-packages/jupyterlab
[I 09:41:35.629 NotebookApp] JupyterLab application directory is /anaconda3/share/jupyter/lab
[I 09:41:35.637 NotebookApp] [nb_conda] enabled
[I 09:41:35.637 NotebookApp] Serving notebooks from local directory: /Users/ed/Git/Blog/learnPandas/codes
[I 09:41:35.637 NotebookApp] The Jupyter Notebook is running at:
[I 09:41:35.637 NotebookApp] http://localhost:8985/?token=03f8483fd2cae6fb30bc9777d5291c7b49108ddcff872a0f
[I 09:41:35.637 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 09:41:35.651 NotebookApp] 
    
    To access the notebook, open this file in a browser:
        file:///Users/ed/Library/Jupyter/runtime/nbserver-63647-open.html
    Or copy and paste one of these URLs:
        http://localhost:8985/?token=03f8483fd2cae6fb30bc9777d5291c7b49108ddcff872a0f
[I 09:41:45.376 NotebookApp] Creating new notebook in 
[I 09:41:46.185 NotebookApp] Kernel started: f6f44dd6-9ff9-45bf-94f9-4c20557238dd
[I 09:41:47.070 NotebookApp] Adapting to protocol v5.1 for kernel f6f44dd6-9ff9-45bf-94f9-4c20557238dd
[I 09:43:46.167 NotebookApp] Saving file at /Untitled1.ipynb
[I 09:45:16.586 NotebookApp] Kernel interrupted: f6f44dd6-9ff9-45bf-94f9-4c20557238dd
[I 09:45:29.386 NotebookApp] Starting buffering for f6f44dd6-9ff9-45bf-94f9-4c20557238dd:43ae02d268d54b7786200e0bad765fd7
[I 09:45:34.554 NotebookApp] Kernel restarted: f6f44dd6-9ff9-45bf-94f9-4c20557238dd
[I 09:45:35.668 NotebookApp] Adapting to protocol v5.1 for kernel f6f44dd6-9ff9-45bf-94f9-4c20557238dd
[I 09:45:35.668 NotebookApp] Restoring connection for f6f44dd6-9ff9-45bf-94f9-4c20557238dd:43ae02d268d54b7786200e0bad765fd7
[I 09:45:35.668 NotebookApp] Replaying 3 buffered messages
[I 09:45:46.166 NotebookApp] Saving file at /Untitled1.ipynb
[I 09:47:46.166 NotebookApp] Saving file at /Untitled1.ipynb
[I 09:49:46.162 NotebookApp] Saving file at /Untitled1.ipynb
[I 09:51:46.187 NotebookApp] Saving file at /Untitled1.ipynb
[I 09:53:46.220 NotebookApp] Saving file at /Untitled1.ipynb
[I 09:55:46.219 NotebookApp] Saving file at /Untitled1.ipynb
[I 09:57:46.219 NotebookApp] Saving file at /Untitled1.ipynb
[I 09:59:46.218 NotebookApp] Saving file at /Untitled1.ipynb
[I 10:01:46.216 NotebookApp] Saving file at /Untitled1.ipynb
[I 10:21:14.801 NotebookApp] Creating new notebook in 
[I 10:21:16.295 NotebookApp] Kernel started: 4b052abb-3140-4ee1-aa92-3f2c275e8c68
[I 10:21:17.082 NotebookApp] Adapting to protocol v5.1 for kernel 4b052abb-3140-4ee1-aa92-3f2c275e8c68
[I 10:23:16.298 NotebookApp] Saving file at /pandas-sort.ipynb
[I 10:25:16.295 NotebookApp] Saving file at /pandas-sort.ipynb
[I 10:27:16.299 NotebookApp] Saving file at /pandas-sort.ipynb
[I 10:33:16.294 NotebookApp] Saving file at /pandas-sort.ipynb
[I 10:35:16.296 NotebookApp] Saving file at /pandas-sort.ipynb
[I 10:37:16.295 NotebookApp] Saving file at /pandas-sort.ipynb
[I 10:39:16.299 NotebookApp] Saving file at /pandas-sort.ipynb
[I 10:41:16.296 NotebookApp] Saving file at /pandas-sort.ipynb
[I 10:41:50.992 NotebookApp] Starting buffering for 4b052abb-3140-4ee1-aa92-3f2c275e8c68:b7684578779c4ccd86e98ed3818f6dbd
[I 10:41:51.309 NotebookApp] Kernel restarted: 4b052abb-3140-4ee1-aa92-3f2c275e8c68
[I 10:41:52.728 NotebookApp] Adapting to protocol v5.1 for kernel 4b052abb-3140-4ee1-aa92-3f2c275e8c68
[I 10:41:52.729 NotebookApp] Restoring connection for 4b052abb-3140-4ee1-aa92-3f2c275e8c68:b7684578779c4ccd86e98ed3818f6dbd
[I 10:41:52.729 NotebookApp] Replaying 5 buffered messages
[I 10:42:19.938 NotebookApp] Starting buffering for 4b052abb-3140-4ee1-aa92-3f2c275e8c68:b7684578779c4ccd86e98ed3818f6dbd
[I 10:42:20.360 NotebookApp] Kernel restarted: 4b052abb-3140-4ee1-aa92-3f2c275e8c68
[I 10:42:20.967 NotebookApp] Adapting to protocol v5.1 for kernel 4b052abb-3140-4ee1-aa92-3f2c275e8c68
[I 10:42:20.968 NotebookApp] Restoring connection for 4b052abb-3140-4ee1-aa92-3f2c275e8c68:b7684578779c4ccd86e98ed3818f6dbd
[I 10:42:20.968 NotebookApp] Replaying 5 buffered messages
[I 10:43:16.337 NotebookApp] Saving file at /pandas-sort.ipynb
[I 10:45:16.333 NotebookApp] Saving file at /pandas-sort.ipynb
[I 10:47:16.335 NotebookApp] Saving file at /pandas-sort.ipynb
[I 10:51:16.340 NotebookApp] Saving file at /pandas-sort.ipynb
[W 10:51:21.145 NotebookApp] 404 GET /notebooks/Untitled1.ipynb?kernel_name=python35564bitpytorchconda72e94a1a4f294f41ae76e825f8204341 (127.0.0.1): No such file or directory: Untitled1.ipynb
[W 10:51:21.166 NotebookApp] 404 GET /notebooks/Untitled1.ipynb?kernel_name=python35564bitpytorchconda72e94a1a4f294f41ae76e825f8204341 (127.0.0.1) 22.45ms referer=http://localhost:8985/notebooks/pandas-sort.ipynb
[W 10:51:22.820 NotebookApp] 404 GET /notebooks/Untitled1.ipynb?kernel_name=python35564bitpytorchconda72e94a1a4f294f41ae76e825f8204341 (127.0.0.1): No such file or directory: Untitled1.ipynb
[W 10:51:22.821 NotebookApp] 404 GET /notebooks/Untitled1.ipynb?kernel_name=python35564bitpytorchconda72e94a1a4f294f41ae76e825f8204341 (127.0.0.1) 2.30ms referer=http://localhost:8985/notebooks/pandas-sort.ipynb
[W 10:51:23.459 NotebookApp] 404 GET /notebooks/Untitled1.ipynb?kernel_name=python35564bitpytorchconda72e94a1a4f294f41ae76e825f8204341 (127.0.0.1): No such file or directory: Untitled1.ipynb
[W 10:51:23.461 NotebookApp] 404 GET /notebooks/Untitled1.ipynb?kernel_name=python35564bitpytorchconda72e94a1a4f294f41ae76e825f8204341 (127.0.0.1) 3.07ms referer=http://localhost:8985/notebooks/pandas-sort.ipynb
[W 10:51:24.281 NotebookApp] 404 GET /notebooks/Untitled1.ipynb?kernel_name=python35564bitpytorchconda72e94a1a4f294f41ae76e825f8204341 (127.0.0.1): No such file or directory: Untitled1.ipynb
[W 10:51:24.283 NotebookApp] 404 GET /notebooks/Untitled1.ipynb?kernel_name=python35564bitpytorchconda72e94a1a4f294f41ae76e825f8204341 (127.0.0.1) 3.23ms referer=http://localhost:8985/notebooks/pandas-sort.ipynb
[I 10:53:16.332 NotebookApp] Saving file at /pandas-sort.ipynb
[I 10:54:28.984 NotebookApp] Creating new notebook in 
[I 10:54:30.400 NotebookApp] Kernel started: 6d7469a3-62ae-4873-8614-2f35c6b5d692
[I 10:54:31.329 NotebookApp] Adapting to protocol v5.1 for kernel 6d7469a3-62ae-4873-8614-2f35c6b5d692
[I 10:56:30.404 NotebookApp] Saving file at /pandas-apply.ipynb
[I 10:58:30.405 NotebookApp] Saving file at /pandas-apply.ipynb
[I 11:09:32.929 NotebookApp] Starting buffering for f6f44dd6-9ff9-45bf-94f9-4c20557238dd:43ae02d268d54b7786200e0bad765fd7
[I 11:09:33.090 NotebookApp] Starting buffering for 4b052abb-3140-4ee1-aa92-3f2c275e8c68:b7684578779c4ccd86e98ed3818f6dbd
[I 11:09:33.796 NotebookApp] Starting buffering for 6d7469a3-62ae-4873-8614-2f35c6b5d692:47ced0d2a7ba4cbd90074e430251e712
[I 11:09:58.205 NotebookApp] Creating new notebook in 
[I 11:09:59.530 NotebookApp] Kernel started: 42915e21-fee7-4f53-8f9b-a7e3b3a1977f
[I 11:10:00.300 NotebookApp] Adapting to protocol v5.1 for kernel 42915e21-fee7-4f53-8f9b-a7e3b3a1977f
[I 11:11:59.532 NotebookApp] Saving file at /pandas-types.ipynb
[I 11:13:59.536 NotebookApp] Saving file at /pandas-types.ipynb
[I 11:17:59.533 NotebookApp] Saving file at /pandas-types.ipynb
[I 11:19:59.797 NotebookApp] Saving file at /pandas-types.ipynb
[I 11:28:01.193 NotebookApp] Saving file at /pandas-types.ipynb
[I 11:30:01.193 NotebookApp] Saving file at /pandas-types.ipynb
[I 11:32:02.522 NotebookApp] Saving file at /pandas-types.ipynb
[I 11:36:29.416 NotebookApp] Saving file at /pandas-types.ipynb
[I 11:43:00.225 NotebookApp] Creating new notebook in 
[I 11:43:01.701 NotebookApp] Kernel started: aa24d827-e848-4d3d-a578-37f865929912
[I 11:43:02.531 NotebookApp] Adapting to protocol v5.1 for kernel aa24d827-e848-4d3d-a578-37f865929912
[I 11:45:01.705 NotebookApp] Saving file at /Untitled1.ipynb
[I 11:47:01.705 NotebookApp] Saving file at /Untitled1.ipynb
[I 11:49:01.707 NotebookApp] Saving file at /Untitled1.ipynb
[I 11:51:01.708 NotebookApp] Saving file at /Untitled1.ipynb
[I 13:55:46.011 NotebookApp] Saving file at /Untitled1.ipynb
[I 13:56:45.035 NotebookApp] Kernel interrupted: aa24d827-e848-4d3d-a578-37f865929912
[I 13:56:46.010 NotebookApp] Kernel interrupted: aa24d827-e848-4d3d-a578-37f865929912
[I 13:56:46.616 NotebookApp] Kernel interrupted: aa24d827-e848-4d3d-a578-37f865929912
[I 13:56:46.999 NotebookApp] Kernel interrupted: aa24d827-e848-4d3d-a578-37f865929912
[I 13:56:47.257 NotebookApp] Kernel interrupted: aa24d827-e848-4d3d-a578-37f865929912
[I 13:56:47.512 NotebookApp] Kernel interrupted: aa24d827-e848-4d3d-a578-37f865929912
[I 13:56:48.002 NotebookApp] Kernel interrupted: aa24d827-e848-4d3d-a578-37f865929912
[I 13:56:48.229 NotebookApp] Kernel interrupted: aa24d827-e848-4d3d-a578-37f865929912
[I 13:56:48.395 NotebookApp] Kernel interrupted: aa24d827-e848-4d3d-a578-37f865929912
[I 13:56:48.568 NotebookApp] Kernel interrupted: aa24d827-e848-4d3d-a578-37f865929912
[I 13:56:48.744 NotebookApp] Kernel interrupted: aa24d827-e848-4d3d-a578-37f865929912
[I 13:56:55.812 NotebookApp] Starting buffering for aa24d827-e848-4d3d-a578-37f865929912:fa233a6175b94a1d879497f6b8c864f3
[I 13:57:00.981 NotebookApp] Kernel restarted: aa24d827-e848-4d3d-a578-37f865929912
[I 13:57:02.077 NotebookApp] Adapting to protocol v5.1 for kernel aa24d827-e848-4d3d-a578-37f865929912
[I 13:57:02.078 NotebookApp] Restoring connection for aa24d827-e848-4d3d-a578-37f865929912:fa233a6175b94a1d879497f6b8c864f3
[I 13:57:45.993 NotebookApp] Saving file at /Untitled1.ipynb
[I 13:59:46.000 NotebookApp] Saving file at /Untitled1.ipynb
[IPKernelApp] ERROR | Exception in message handler:
Traceback (most recent call last):
  File "/anaconda3/envs/pytorch/lib/python3.5/site-packages/ipykernel/kernelbase.py", line 267, in dispatch_shell
    yield gen.maybe_future(handler(stream, idents, msg))
  File "/anaconda3/envs/pytorch/lib/python3.5/site-packages/tornado/gen.py", line 1133, in run
    value = future.result()
  File "/anaconda3/envs/pytorch/lib/python3.5/asyncio/futures.py", line 294, in result
    raise self._exception
  File "/anaconda3/envs/pytorch/lib/python3.5/site-packages/tornado/gen.py", line 1141, in run
    yielded = self.gen.throw(*exc_info)
  File "/anaconda3/envs/pytorch/lib/python3.5/site-packages/ipykernel/kernelbase.py", line 534, in execute_request
    user_expressions, allow_stdin,
  File "/anaconda3/envs/pytorch/lib/python3.5/site-packages/tornado/gen.py", line 1133, in run
    value = future.result()
  File "/anaconda3/envs/pytorch/lib/python3.5/asyncio/futures.py", line 294, in result
    raise self._exception
  File "/anaconda3/envs/pytorch/lib/python3.5/site-packages/tornado/gen.py", line 326, in wrapper
    yielded = next(result)
  File "/anaconda3/envs/pytorch/lib/python3.5/site-packages/ipykernel/ipkernel.py", line 294, in do_execute
    res = shell.run_cell(code, store_history=store_history, silent=silent)
  File "/anaconda3/envs/pytorch/lib/python3.5/site-packages/ipykernel/zmqshell.py", line 536, in run_cell
    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
  File "/anaconda3/envs/pytorch/lib/python3.5/site-packages/IPython/core/interactiveshell.py", line 2819, in run_cell
    self.events.trigger('post_execute')
  File "/anaconda3/envs/pytorch/lib/python3.5/site-packages/IPython/core/interactiveshell.py", line 2819, in run_cell
    self.events.trigger('post_execute')
  File "/anaconda3/envs/pytorch/lib/python3.5/bdb.py", line 48, in trace_dispatch
    return self.dispatch_line(frame)
  File "/anaconda3/envs/pytorch/lib/python3.5/bdb.py", line 67, in dispatch_line
    if self.quitting: raise BdbQuit
bdb.BdbQuit
[I 14:01:46.000 NotebookApp] Saving file at /Untitled1.ipynb
[I 14:03:45.994 NotebookApp] Saving file at /Untitled1.ipynb
[IPKernelApp] ERROR | Exception in message handler:
Traceback (most recent call last):
  File "/anaconda3/envs/pytorch/lib/python3.5/site-packages/ipykernel/kernelbase.py", line 267, in dispatch_shell
    yield gen.maybe_future(handler(stream, idents, msg))
  File "/anaconda3/envs/pytorch/lib/python3.5/site-packages/tornado/gen.py", line 1133, in run
    value = future.result()
  File "/anaconda3/envs/pytorch/lib/python3.5/asyncio/futures.py", line 294, in result
    raise self._exception
  File "/anaconda3/envs/pytorch/lib/python3.5/site-packages/tornado/gen.py", line 1141, in run
    yielded = self.gen.throw(*exc_info)
  File "/anaconda3/envs/pytorch/lib/python3.5/site-packages/ipykernel/kernelbase.py", line 534, in execute_request
    user_expressions, allow_stdin,
  File "/anaconda3/envs/pytorch/lib/python3.5/site-packages/tornado/gen.py", line 1133, in run
    value = future.result()
  File "/anaconda3/envs/pytorch/lib/python3.5/asyncio/futures.py", line 294, in result
    raise self._exception
  File "/anaconda3/envs/pytorch/lib/python3.5/site-packages/tornado/gen.py", line 326, in wrapper
    yielded = next(result)
  File "/anaconda3/envs/pytorch/lib/python3.5/bdb.py", line 54, in trace_dispatch
    return self.dispatch_exception(frame, arg)
  File "/anaconda3/envs/pytorch/lib/python3.5/bdb.py", line 119, in dispatch_exception
    if self.quitting: raise BdbQuit
bdb.BdbQuit
[IPKernelApp] ERROR | Exception in message handler:
Traceback (most recent call last):
  File "/anaconda3/envs/pytorch/lib/python3.5/site-packages/ipykernel/kernelbase.py", line 267, in dispatch_shell
    yield gen.maybe_future(handler(stream, idents, msg))
  File "/anaconda3/envs/pytorch/lib/python3.5/site-packages/tornado/gen.py", line 1133, in run
    value = future.result()
  File "/anaconda3/envs/pytorch/lib/python3.5/asyncio/futures.py", line 294, in result
    raise self._exception
  File "/anaconda3/envs/pytorch/lib/python3.5/site-packages/tornado/gen.py", line 1141, in run
    yielded = self.gen.throw(*exc_info)
  File "/anaconda3/envs/pytorch/lib/python3.5/site-packages/ipykernel/kernelbase.py", line 534, in execute_request
    user_expressions, allow_stdin,
  File "/anaconda3/envs/pytorch/lib/python3.5/site-packages/tornado/gen.py", line 1133, in run
    value = future.result()
  File "/anaconda3/envs/pytorch/lib/python3.5/asyncio/futures.py", line 294, in result
    raise self._exception
  File "/anaconda3/envs/pytorch/lib/python3.5/site-packages/tornado/gen.py", line 326, in wrapper
    yielded = next(result)
  File "/anaconda3/envs/pytorch/lib/python3.5/bdb.py", line 54, in trace_dispatch
    return self.dispatch_exception(frame, arg)
  File "/anaconda3/envs/pytorch/lib/python3.5/bdb.py", line 119, in dispatch_exception
    if self.quitting: raise BdbQuit
bdb.BdbQuit
[I 14:05:45.999 NotebookApp] Saving file at /Untitled1.ipynb
[I 14:07:11.275 NotebookApp] Kernel interrupted: aa24d827-e848-4d3d-a578-37f865929912
[I 14:07:15.726 NotebookApp] Kernel interrupted: aa24d827-e848-4d3d-a578-37f865929912
[I 14:07:17.757 NotebookApp] Kernel interrupted: aa24d827-e848-4d3d-a578-37f865929912
[I 14:07:18.356 NotebookApp] Kernel interrupted: aa24d827-e848-4d3d-a578-37f865929912
[I 14:07:18.821 NotebookApp] Kernel interrupted: aa24d827-e848-4d3d-a578-37f865929912
[I 14:07:20.665 NotebookApp] Starting buffering for aa24d827-e848-4d3d-a578-37f865929912:fa233a6175b94a1d879497f6b8c864f3
[I 14:07:25.818 NotebookApp] Kernel restarted: aa24d827-e848-4d3d-a578-37f865929912
[I 14:07:26.822 NotebookApp] Adapting to protocol v5.1 for kernel aa24d827-e848-4d3d-a578-37f865929912
[I 14:07:26.823 NotebookApp] Restoring connection for aa24d827-e848-4d3d-a578-37f865929912:fa233a6175b94a1d879497f6b8c864f3
[I 14:07:46.022 NotebookApp] Saving file at /Untitled1.ipynb
[I 14:08:24.957 NotebookApp] Starting buffering for aa24d827-e848-4d3d-a578-37f865929912:fa233a6175b94a1d879497f6b8c864f3
[I 14:58:20.957 NotebookApp] Starting buffering for 42915e21-fee7-4f53-8f9b-a7e3b3a1977f:03347234bcbc44568b837489e4f66596
[C 21:59:48.157 NotebookApp] received signal 15, stopping
[I 21:59:48.179 NotebookApp] Shutting down 5 kernels
[I 21:59:49.831 NotebookApp] Kernel shutdown: f6f44dd6-9ff9-45bf-94f9-4c20557238dd
[I 21:59:49.833 NotebookApp] Kernel shutdown: 4b052abb-3140-4ee1-aa92-3f2c275e8c68
[I 21:59:49.835 NotebookApp] Kernel shutdown: 6d7469a3-62ae-4873-8614-2f35c6b5d692
[I 21:59:49.837 NotebookApp] Kernel shutdown: 42915e21-fee7-4f53-8f9b-a7e3b3a1977f
